Repository TeamEpochGithub/epochlib, pull requests merged in 2024-03, with the labels that each got.

#15 12 refactor torch block
  .coverage
  README.md
  epochalyst/_core/_logging/_logger.py
  epochalyst/_core/_pipeline/_custom_data_parallel.py
  epochalyst/logging/logger.py
  epochalyst/pipeline/caching/dask_array/base_cache_block.py
  epochalyst/pipeline/model/training/__init__.py
  epochalyst/pipeline/model/training/_utils/__init__.py
  epochalyst/pipeline/model/training/_utils/_collate_fn.py
  epochalyst/pipeline/model/training/_utils/torch_layerwise_lr.py
  epochalyst/pipeline/model/training/pretrain_block.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/trainers/torch_block.py
  requirements.txt
  tests/pipeline/model/training/test_pretrain_block.py
  tests/pipeline/model/training/test_torch_trainer.py
Labels: refactor

#17 13 update test coverage
  .gitignore
  .pre-commit-config.yaml
  epochalyst/_core/_imports/_self.py
  epochalyst/pipeline/caching/dask_array/base_cache_block.py
  epochalyst/pipeline/model/training/_utils/__init__.py
  epochalyst/pipeline/model/training/_utils/dask_dataset.py
  epochalyst/pipeline/model/training/pretrain_block.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training.py
  requirements.txt
  tests/_core/_imports/test__self.py
  tests/_core/_logging/test__logger.py
  tests/pipeline/caching/dask_array/test_base_cache_block.py
  tests/pipeline/model/test_model.py
  tests/pipeline/model/training/test_pretrain_block.py
  tests/pipeline/model/training/test_torch_trainer.py
  tests/pipeline/model/training/test_training.py
Labels: testing

#18 16 turn trainer and transformer into blocks
  epochalyst/_core/_logging/_logger.py
  epochalyst/pipeline/caching/dask_array/base_cache_block.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/transformation/__init__.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  tests/pipeline/caching/dask_array/test_base_cache_block.py
  tests/pipeline/model/transformation/test_transformation.py
  tests/pipeline/model/transformation/test_transformation_block.py
Labels: testing

#21 Update python-package-testing.yml
  .github/workflows/python-package-testing.yml
Labels: testing

#25 Refactor caching
  epochalyst/_core/_caching/_cacher.py
  epochalyst/pipeline/caching/__init__.py
  epochalyst/pipeline/caching/dask_array/__init__.py
  epochalyst/pipeline/caching/dask_array/base_cache_block.py
  epochalyst/pipeline/caching/dask_array/cache_column_block.py
  epochalyst/pipeline/caching/dask_array/cache_full_block.py
  epochalyst/pipeline/caching/error.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  pyproject.toml
  requirements.txt
  tests/_core/_caching/test__cacher.py
  tests/pipeline/caching/dask_array/test_base_cache_block.py
  tests/pipeline/caching/dask_array/test_cache_column_block.py
  tests/pipeline/caching/dask_array/test_full_block.py
  tests/pipeline/model/transformation/test_transformation.py
  tests/pipeline/model/transformation/test_transformation_block.py
Labels: enhancement, pipeline

#33 Better documentation
  docs/conf.py
  epochalyst/__init__.py
  epochalyst/_core/__init__.py
  epochalyst/_core/_caching/__init__.py
  epochalyst/_core/_logging/__init__.py
  epochalyst/_core/_logging/_logger.py
  epochalyst/_core/_pipeline/__init__.py
  epochalyst/logging/__init__.py
  epochalyst/pipeline/model/training/__init__.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/transformation/__init__.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  pyproject.toml
Labels: documentation

#36 Add caching to the trainer block
  epochalyst/_core/_caching/_cacher.py
  epochalyst/_core/_logging/_logger.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  tests/pipeline/model/training/test_torch_trainer.py
  tests/pipeline/model/training/test_training_block.py
  tests/pipeline/model/transformation/test_transformation_block.py
Labels: enhancement

#41 Support Python 3.12
  .github/workflows/publish-package.yml
  .github/workflows/python-package-testing.yml
  README.md
  pyproject.toml
  requirements.txt
Labels: good first issue

#49 Add sphinx requirements
  docs/requirements.txt
Labels: documentation

#50 Delete .vscode directory
  .gitignore
  .vscode/settings.json
Labels: bug

#45 Add logging to cacher
  epochalyst/_core/_caching/_cacher.py
  tests/_core/_caching/test__cacher.py
  tests/pipeline/model/training/test_training.py
  tests/pipeline/model/training/test_training_block.py
  tests/pipeline/model/transformation/test_transformation.py
  tests/pipeline/model/transformation/test_transformation_block.py
Labels: logging

#46 Version 0.1.2
  .github/workflows/publish-package.yml
  .github/workflows/python-package-testing.yml
  .gitignore
  .vscode/settings.json
  README.md
  docs/requirements.txt
  epochalyst/_core/_caching/_cacher.py
  epochalyst/pipeline/model/model.py
  epochalyst/pipeline/model/training/pretrain_block.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  pyproject.toml
  requirements.txt
  tests/_core/_caching/test__cacher.py
  tests/pipeline/model/training/test_pretrain_block.py
  tests/pipeline/model/training/test_training.py
  tests/pipeline/model/training/test_training_block.py
  tests/pipeline/model/transformation/test_transformation.py
  tests/pipeline/model/transformation/test_transformation_block.py
Labels: enhancement

#53 Update version and dependencies in pyproject.toml
  pyproject.toml
Labels: bug

#59 Update torch trainer documentation
  .gitignore
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/transformation/transformation.py
Labels: documentation

#60 v0.1.3
  .gitignore
  epochalyst/_core/_caching/_cacher.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  pyproject.toml
  requirements.txt
  tests/pipeline/model/training/test_training.py
  tests/pipeline/model/training/test_training_block.py
  tests/pipeline/model/transformation/test_transformation.py
  tests/pipeline/model/transformation/test_transformation_block.py
Labels: documentation, refactor

#69 Add Epochalyst Logo to Documentation and README.md
  README.md
  docs/_static/images/logo/Epochalyst_Icon.png
  docs/_static/images/logo/Epochalyst_Logo_Dark.png
  docs/_static/images/logo/Epochalyst_Logo_Light.png
  docs/_static/logo.css
  docs/conf.py
  docs/index.rst
  mypy.ini
  pyproject.toml
Labels: 04 - Documentation

#70 Remove multiply batch_size line
  epochalyst/pipeline/model/training/torch_trainer.py
Labels: 00 - Bug

#72 Bug epochalyst should create tm folder when it does not exist when saving models
  .pre-commit-config.yaml
  epochalyst/_core/_pipeline/_custom_data_parallel.py
  epochalyst/logging/section_separator.py
  epochalyst/pipeline/model/training/torch_trainer.py
  pyproject.toml
  tests/pipeline/model/training/test_torch_trainer.py
Labels: 00 - Bug

#76 V0.1.4
  .pre-commit-config.yaml
  README.md
  docs/_static/images/logo/Epochalyst_Icon.png
  docs/_static/images/logo/Epochalyst_Logo_Dark.png
  docs/_static/images/logo/Epochalyst_Logo_Light.png
  docs/_static/logo.css
  docs/conf.py
  docs/index.rst
  epochalyst/_core/_pipeline/_custom_data_parallel.py
  epochalyst/logging/section_separator.py
  epochalyst/pipeline/model/training/torch_trainer.py
  mypy.ini
  pyproject.toml
  tests/pipeline/model/training/test_torch_trainer.py
Labels: 10 - Release

#78 Create new workflow
  .github/workflows/main-branch-testing.yml
  .github/workflows/version-branch-testing.yml
Labels: 03 - CI/CD

#81 Add the custom line plot to log to external
  epochalyst/pipeline/model/training/torch_trainer.py
Labels: 01 - Enhancement

#82 Concat datasets abstraction
  epochalyst/pipeline/model/training/torch_trainer.py
Labels: 02 - Refactor

#87 Update logging to wandb
  epochalyst/pipeline/model/training/torch_trainer.py
Labels: 02 - Refactor

#90 Update workflows
  .github/workflows/main-branch-testing.yml
  .github/workflows/version-branch-testing.yml
  README.md
Labels: 01 - Enhancement

#92 Update torch_trainer.py
  epochalyst/pipeline/model/training/torch_trainer.py
Labels: 02 - Refactor

#93 V0.1.7
  epochalyst/pipeline/model/training/torch_trainer.py
  pyproject.toml
Labels: 10 - Release

#95 Add Polars Dataframe output cache type
  .github/workflows/main-branch-testing.yml
  .github/workflows/version-branch-testing.yml
  .pre-commit-config.yaml
  epochalyst/_core/_caching/_cacher.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  pyproject.toml
  requirements.txt
  tests/_core/_caching/test__cacher.py
Labels: 01 - Enhancement, 07 - Caching

#99 Translate docstrings from markdown to rst
  epochalyst/_core/_caching/_cacher.py
  epochalyst/_core/_logging/_logger.py
  epochalyst/pipeline/model/training/pretrain_block.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
Labels: 04 - Documentation

#100 Optional imports
  README.md
  pyproject.toml
Labels: 02 - Refactor
