Repository TeamEpochGithub/epochlib, pull requests merged in 2024-06, with the labels that each got.

#154 Fix bug in batch_to_device in torch trainer
  epochalyst/pipeline/model/training/torch_trainer.py
Labels: 00 - Bug, 09 - Block

#166 ENH: Check if tm folder exists
  epochalyst/pipeline/model/training/torch_trainer.py
Labels: 01 - Enhancement

#167 Raise error if model_name is not specified in trainer
  epochalyst/pipeline/model/training/torch_trainer.py
  tests/pipeline/model/training/test_torch_trainer.py
Labels: 02 - Refactor

#169 Implement a parameter for pretraining with timm
  epochalyst/pipeline/model/training/models/timm.py
Labels: 02 - Refactor

#171 Make collate_fn an argument for the torch trainer class so it can be …
  epochalyst/pipeline/model/training/torch_trainer.py
Labels: 02 - Refactor

#174 Rename test to validation
  .github/workflows/version-branch-testing.yml
  epochalyst/pipeline/model/training/torch_trainer.py
  tests/pipeline/model/training/test_torch_trainer.py
Labels: 02 - Refactor

#175 V0.3.4
  .github/workflows/version-branch-testing.yml
  epochalyst/pipeline/model/training/models/timm.py
  epochalyst/pipeline/model/training/torch_trainer.py
  pyproject.toml
  tests/_core/_caching/test__cacher.py
  tests/_core/_logging/test__logger.py
  tests/cache/README.md
  tests/conftest.py
  tests/constants.py
  tests/pipeline/model/test_model.py
  tests/pipeline/model/training/augmentation/test_image_augmentations.py
  tests/pipeline/model/training/augmentation/test_time_series_augmentations.py
  tests/pipeline/model/training/augmentation/test_utils.py
  tests/pipeline/model/training/models/test_timm.py
  tests/pipeline/model/training/test_pretrain_block.py
  tests/pipeline/model/training/test_torch_trainer.py
  tests/pipeline/model/training/test_training.py
  tests/pipeline/model/training/test_training_block.py
  tests/pipeline/model/transformation/test_transformation.py
  tests/pipeline/model/transformation/test_transformation_block.py
  tests/pipeline/test_ensemble.py
  tests/util.py
Labels: 12 - Release

#185 Add `CITATION.cff`
  CITATION.cff
Labels: 01 - Enhancement

#200 Update pre-commit config
  .pre-commit-config.yaml
  CITATION.cff
  epochalyst/_core/_caching/_cacher.py
  epochalyst/_core/_logging/_logger.py
  epochalyst/pipeline/ensemble.py
  epochalyst/pipeline/model/model.py
  epochalyst/pipeline/model/training/models/timm.py
  epochalyst/pipeline/model/training/pretrain_block.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/training/utils/tensor_functions.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  mypy.ini
  pyproject.toml
  ruff.toml
Labels: 01 - Enhancement

#187 Fix default patience value set to 1
  epochalyst/pipeline/model/training/torch_trainer.py
  tests/pipeline/model/training/test_torch_trainer.py
Labels: 00 - Bug

#201 ENH: Allow project to be managed with rye
  .github/workflows/main-branch-testing.yml
  .github/workflows/version-branch-testing.yml
  .python-version
  epochalyst/_core/_caching/_cacher.py
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  requirements.txt
Labels: 01 - Enhancement

#205 Add `dependabot.yml`
  .github/dependabot.yml
Labels: 01 - Enhancement

#194 ENH: Add birdclef audio augmentations
  epochalyst/pipeline/model/training/augmentation/time_series_augmentations.py
  epochalyst/pipeline/model/training/augmentation/utils.py
  epochalyst/pipeline/model/training/utils/recursive_repr.py
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  tests/pipeline/model/training/augmentation/test_audio/white_noise.wav
  tests/pipeline/model/training/augmentation/test_time_series_augmentations.py
  tests/pipeline/model/training/augmentation/test_utils.py
  tests/pipeline/test_recursive_repr.py
Labels: 01 - Enhancement

#195 ENH: Add onnxopenvinocompile option to trainer
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/utils/__init__.py
  epochalyst/pipeline/model/training/utils/get_dependencies.py
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  requirements.txt
  tests/pipeline/model/training/test_torch_trainer.py
  tests/pipeline/model/training/utils/test_get_dependencies.py
Labels: 01 - Enhancement

#208 ENH: Only test on Py3.10 for version branches
  .github/workflows/publish-package.yml
  .github/workflows/version-branch-testing.yml
Labels: 03 - CI/CD

#204 ENH: Added default logger, Timm class uses kwargs
  .gitignore
  epochalyst/_core/_caching/_cacher.py
  epochalyst/_core/_logging/__init__.py
  epochalyst/_core/_logging/_logger.py
  epochalyst/logging/__init__.py
  epochalyst/logging/logger.py
  epochalyst/logging/section_separator.py
  epochalyst/pipeline/model/training/models/timm.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  tests/_core/_caching/test__cacher.py
  tests/_core/_logging/test__logger.py
  tests/logging/test_logger.py
  tests/pipeline/model/training/models/test_timm.py
  tests/pipeline/model/training/test_torch_trainer.py
  tests/pipeline/model/transformation/test_transformation_block.py
Labels: 01 - Enhancement

#213 CI: Configure pre-commit.ci
  .github/workflows/main-branch-testing.yml
  .github/workflows/static-analysis.yml
  .github/workflows/version-branch-testing.yml
  .pre-commit-config.yaml
Labels: 03 - CI/CD

#216 DOC: Add optional dependencies description to `README.md`
  README.md
  requirements.txt
Labels: 04 - Documentation
