Repository TeamEpochGithub/epochlib, pull requests merged in 2024-04, with the labels that each got.

#102 Ensembling
  epochalyst/pipeline/ensemble.py
  epochalyst/pipeline/model/model.py
  epochalyst/pipeline/model/training/torch_trainer.py
  pyproject.toml
  requirements.txt
  tests/pipeline/model/test_model.py
  tests/pipeline/test_ensemble.py
Labels: 01 - Enhancement

#104 Improve caching for pipelines
  epochalyst/pipeline/model/training/training.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  pyproject.toml
  requirements.txt
  tests/pipeline/model/training/test_training.py
  tests/pipeline/model/transformation/test_transformation.py
Labels: 01 - Enhancement

#105 V0.2
  .github/workflows/main-branch-testing.yml
  .github/workflows/version-branch-testing.yml
  .pre-commit-config.yaml
  README.md
  epochalyst/_core/_caching/_cacher.py
  epochalyst/_core/_logging/_logger.py
  epochalyst/pipeline/ensemble.py
  epochalyst/pipeline/model/model.py
  epochalyst/pipeline/model/training/pretrain_block.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  pyproject.toml
  requirements.txt
  tests/_core/_caching/test__cacher.py
  tests/pipeline/model/test_model.py
  tests/pipeline/model/training/test_training.py
  tests/pipeline/model/transformation/test_transformation.py
  tests/pipeline/test_ensemble.py
Labels: 10 - Release

#117 Optional imports not actually optional
  epochalyst/_core/_caching/_cacher.py
  pyproject.toml
  requirements.txt
Labels: 00 - Bug

#119 Save to external for models
  epochalyst/pipeline/model/training/torch_trainer.py
Labels: 01 - Enhancement

#121 Ability to disable early stopping
  epochalyst/pipeline/model/training/torch_trainer.py
  tests/pipeline/model/training/test_torch_trainer.py
Labels: 01 - Enhancement

#111 Add `read_args` and `store_args` to `cache_args`
  epochalyst/_core/_caching/_cacher.py
  epochalyst/pipeline/ensemble.py
  epochalyst/pipeline/model/model.py
  epochalyst/pipeline/model/training/training.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
Labels: 01 - Enhancement, 07 - Caching

#128 Add timm wrapper for models
  .pre-commit-config.yaml
  epochalyst/__init__.py
  epochalyst/_core/_caching/_cacher.py
  epochalyst/_core/_logging/_logger.py
  epochalyst/logging/section_separator.py
  epochalyst/pipeline/ensemble.py
  epochalyst/pipeline/model/model.py
  epochalyst/pipeline/model/training/models/__init__.py
  epochalyst/pipeline/model/training/models/timm.py
  epochalyst/pipeline/model/training/pretrain_block.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  pyproject.toml
  requirements.txt
  tests/_core/_caching/test__cacher.py
  tests/pipeline/model/training/models/test_timm.py
Labels: 01 - Enhancement

#118 Add saving of folds.
  epochalyst/pipeline/model/training/torch_trainer.py
  tests/pipeline/model/training/test_torch_trainer.py
Labels: 02 - Refactor

#129 Add augmentations implemented in q3
  .pre-commit-config.yaml
  README.md
  epochalyst/pipeline/model/training/augmentation/__init__.py
  epochalyst/pipeline/model/training/augmentation/image_augmentations.py
  epochalyst/pipeline/model/training/augmentation/time_series_augmentations.py
  epochalyst/pipeline/model/training/augmentation/utils.py
  epochalyst/pipeline/model/training/models/timm.py
  requirements.txt
  tests/pipeline/model/training/augmentation/test_image_augmentations.py
  tests/pipeline/model/training/augmentation/test_time_series_augmentations.py
  tests/pipeline/model/training/augmentation/test_utils.py
Labels: 01 - Enhancement

#120 Add argument in torch trainer whether to predict or not
  epochalyst/pipeline/model/training/torch_trainer.py
  tests/pipeline/model/training/test_torch_trainer.py
Labels: 02 - Refactor

#130 V0.3
  .pre-commit-config.yaml
  README.md
  epochalyst/__init__.py
  epochalyst/_core/_caching/_cacher.py
  epochalyst/_core/_logging/_logger.py
  epochalyst/logging/section_separator.py
  epochalyst/pipeline/ensemble.py
  epochalyst/pipeline/model/model.py
  epochalyst/pipeline/model/training/augmentation/__init__.py
  epochalyst/pipeline/model/training/augmentation/image_augmentations.py
  epochalyst/pipeline/model/training/augmentation/time_series_augmentations.py
  epochalyst/pipeline/model/training/augmentation/utils.py
  epochalyst/pipeline/model/training/models/__init__.py
  epochalyst/pipeline/model/training/models/timm.py
  epochalyst/pipeline/model/training/pretrain_block.py
  epochalyst/pipeline/model/training/torch_trainer.py
  epochalyst/pipeline/model/training/training.py
  epochalyst/pipeline/model/training/training_block.py
  epochalyst/pipeline/model/transformation/transformation.py
  epochalyst/pipeline/model/transformation/transformation_block.py
  pyproject.toml
  requirements.txt
  tests/_core/_caching/test__cacher.py
  tests/pipeline/model/training/augmentation/test_image_augmentations.py
  tests/pipeline/model/training/augmentation/test_time_series_augmentations.py
  tests/pipeline/model/training/augmentation/test_utils.py
  tests/pipeline/model/training/models/test_timm.py
  tests/pipeline/model/training/test_torch_trainer.py
Labels: 11 - Release

#134 Fix epochalyst predictions
  epochalyst/pipeline/model/training/torch_trainer.py
Labels: 00 - Bug

#135 V0.3.1
  epochalyst/pipeline/model/training/torch_trainer.py
  pyproject.toml
  tests/pipeline/model/training/test_torch_trainer.py
Labels: 11 - Release

#137 Fix bug in predict
  epochalyst/pipeline/model/training/torch_trainer.py
  pyproject.toml
Labels: 00 - Bug

#138 V0.3.2
  epochalyst/pipeline/model/training/torch_trainer.py
  pyproject.toml
Labels: 11 - Release

#139 Deploy documentation on GitHub pages
  .github/workflows/publish-docs.yaml
  docs/index.rst
  docs/readme_link.rst
  docs/requirements.txt
Labels: 04 - Documentation
